library(dplyr)
library(missForest)
library(naniar)
library(tidyr)
library(mice)
library(randomForest)
library(caret)
library(tidyr)
library("writexl")
library(keras)
library(mlbench)
library(dplyr)
library(magrittr)
library(neuralnet)
library(e1071)
library(nnet)
library(stringr)
library(rpart)
library(ROSE)
library(lightgbm)
library(xgboost)
library(tidyverse)
library(adabag)
data <- read.csv2("train.csv",sep =",")
test <- read.csv2("test.csv",sep =",")
head(data)
str(data)
colnames(data)<-str_to_sentence(colnames(data))
colnames(data) <- str_to_lower(colnames(data))
colnames(data)[c(1,2,10,11)] <- c("id","pokedex_number","speed_atk","speed_def")
colnames(data)
data %>% count(type.2)
data %>% count(generation)
data <- data %>% mutate(type.1=str_to_lower(type.1),
                        type.2=str_to_lower(type.2))
data <- data %>% mutate(
  type.1=str_trim(type.1,side="left"),
  type.2=str_trim(type.2,side="left"))
data <- data %>% mutate(
  type.1=as.factor(type.1),
  type.2=as.factor(type.2))
data <- data %>% select(-name,-id)
data$generation <- as.factor(data$generation)
data$legendary <- as.factor(data$legendary)
data <- data %>%
  select(legendary, everything())